x = input("Digite algo: ")
type_of_x = type(x)
print("{} é do type {}".format(x, type_of_x))
print("Só tem espaços? {}".format(x.isspace()))
print("É um número? {}".format(x.isnumeric()))
print("É alfabético? {}".format(x.isalpha()))
print("É alfanumérico? {}".format(x.isalnum()))
print("Somente maiúsculas? {}".format(x.isupper()))
print("Somente minúsculas? {}".format(x.islower()))
print("Capitalizada? {}".format(x.istitle()))